INSERT INTO `Provinces`(`id`, `name`) VALUES (NULL, 'Azúa');
INSERT INTO `Provinces`(`id`, `name`) VALUES (NULL, 'Baoruco');
INSERT INTO `Provinces`(`id`, `name`) VALUES (NULL, 'Barahona');
INSERT INTO `Provinces`(`id`, `name`) VALUES (NULL, 'Dajabón');
INSERT INTO `Provinces`(`id`, `name`) VALUES (NULL, 'Distrito Nacional');
INSERT INTO `Provinces`(`id`, `name`) VALUES (NULL, 'Duarte');
INSERT INTO `Provinces`(`id`, `name`) VALUES (NULL, 'Elías Piña');
INSERT INTO `Provinces`(`id`, `name`) VALUES (NULL, 'El Seibo');
INSERT INTO `Provinces`(`id`, `name`) VALUES (NULL, 'Espaillat');
INSERT INTO `Provinces`(`id`, `name`) VALUES (NULL, 'Hato Mayor');
INSERT INTO `Provinces`(`id`, `name`) VALUES (NULL, 'Independencia');
INSERT INTO `Provinces`(`id`, `name`) VALUES (NULL, 'La Altagracia');
INSERT INTO `Provinces`(`id`, `name`) VALUES (NULL, 'La Romana');
INSERT INTO `Provinces`(`id`, `name`) VALUES (NULL, 'La Vega');
INSERT INTO `Provinces`(`id`, `name`) VALUES (NULL, 'Maria Trinidad Sanchez');
INSERT INTO `Provinces`(`id`, `name`) VALUES (NULL, 'Monseñor Nouel');
INSERT INTO `Provinces`(`id`, `name`) VALUES (NULL, 'Monte Cristi');
INSERT INTO `Provinces`(`id`, `name`) VALUES (NULL, 'Monte Plata');
INSERT INTO `Provinces`(`id`, `name`) VALUES (NULL, 'Pedernales');
INSERT INTO `Provinces`(`id`, `name`) VALUES (NULL, 'Peravia');
INSERT INTO `Provinces`(`id`, `name`) VALUES (NULL, 'Puerto Plata');
INSERT INTO `Provinces`(`id`, `name`) VALUES (NULL, 'Salcedo');
INSERT INTO `Provinces`(`id`, `name`) VALUES (NULL, 'Samaná');
INSERT INTO `Provinces`(`id`, `name`) VALUES (NULL, 'Sánchez Ramirez');
INSERT INTO `Provinces`(`id`, `name`) VALUES (NULL, 'San Cristobal');
INSERT INTO `Provinces`(`id`, `name`) VALUES (NULL, 'San José de Ocoa');
INSERT INTO `Provinces`(`id`, `name`) VALUES (NULL, 'San Juan');
INSERT INTO `Provinces`(`id`, `name`) VALUES (NULL, 'San Pedro de Macorís');
INSERT INTO `Provinces`(`id`, `name`) VALUES (NULL, 'Santiago');
INSERT INTO `Provinces`(`id`, `name`) VALUES (NULL, 'Santiago Rodríguez');
INSERT INTO `Provinces`(`id`, `name`) VALUES (NULL, 'Santo Domingo');
INSERT INTO `Provinces`(`id`, `name`) VALUES (NULL, 'Valverde');